[package]
name = "zstd-builder"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
common = { path = "../../crates/common" }
email = { path = "../../crates/email" }
groupware = { path = "../../crates/groupware" }
jmap_proto = { path = "../../crates/jmap-proto" }
nlp = { path = "../../crates/nlp" }
smtp = { path = "../../crates/smtp" }
store = { path = "../../crates/store", features = ["test_mode"] }
types = { path = "../../crates/types" }
utils = { path = "../../crates/utils" }
calcard = { version = "0.4", features = ["rkyv"] }
mail-builder = { version = "2.0" }
mail-parser = { version = "1.0", features = ["full_encoding"] }
rkyv = { version = "0.8.18", features = ["little_endian", "unaligned"] }
serde_json = "1.0"
sieve-rs = { version = "2.0" }
smtp-proto = { version = "0.2.3", features = ["rkyv"] }
xxhash-rust = { version = "0.8.18", features = ["xxh3"] }
zstd = { version = "0.13", features = ["zdict_builder", "experimental"] }

[patch.crates-io]
calcard = { path = "../../../calcard" }
dns-update = { path = "../../../dns-update" }
jmap-tools = { path = "../../../jmap-tools" }
mail-auth = { path = "../../../mail-auth" }
mail-builder = { path = "../../../mail-builder" }
encodify = { path = "../../../encodify" }
mail-parser = { path = "../../../mail-parser" }
sieve-rs = { path = "../../../sieve" }

[profile.release]
opt-level = 2
debug = false
