/*
 * SPDX-FileCopyrightText: 2020 Stalwart Labs LLC <hello@stalw.art>
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-SEL
 */

use super::{ActiveScript, ArchivedSieveScript, Bytecode, SeenIdHash, SieveScript};
use crate::{
    cache::{MessageCacheFetch, mailbox::MailboxCacheAccess},
    mailbox::{INBOX_ID, TRASH_ID, manage::MailboxFnc},
    message::{
        delivery::{AutogeneratedMessage, IngestRecipient},
        ingest::{EmailIngest, IngestEmail, IngestSource, IngestedEmail},
    },
    sieve::VacationResponse,
};
use common::{
    MessageStoreCache, Server, auth::AccessToken, config::mailstore::spamfilter::spam_status,
    scripts::plugins::PluginContext,
};
use mail_builder::headers::date::Date;
use mail_parser::{HeaderName, MessageParser};
use sieve::{
    Arena, Context, Envelope, Handler, Input, Mailbox, MessageSource, Recipient, Reply,
    ScriptArena, Sieve, SieveAction, Status,
    compiler::grammar::actions::action_redirect::Notify,
    runtime::{Script, Variable},
};
use std::{borrow::Cow, sync::Arc};
use std::{future::Future, str::FromStr};
use store::{
    Serialize, ValueKey,
    ahash::AHashMap,
    dispatch::lookup::KeyValue,
    write::{Archive, ArchiveBytes, ArchiveVersion, Archiver, BatchBuilder, ValueClass},
};
use trc::{AddContext, SieveEvent, SmtpEvent};
use types::{
    blob_hash::BlobHash,
    collection::Collection,
    field::{PrincipalField, SieveField},
    id::Id,
    keyword::Keyword,
    special_use::SpecialUse,
};

struct SieveMessage<'x> {
    pub raw_message: Cow<'x, [u8]>,
    pub file_into: Vec<u32>,
    pub flags: Vec<Keyword>,
}

struct SieveHandler<'x> {
    server: &'x Server,
    session_id: u64,
    account_id: u32,
    script_hash: u32,
    cache: Arc<MessageStoreCache>,
    mail_from: &'x str,
    server_name: &'x str,
    mail_max_size: usize,
    max_received_headers: usize,
    received_headers: usize,
    messages: Vec<SieveMessage<'x>>,
    autogenerated: &'x mut Vec<AutogeneratedMessage>,
    checked_ids: AHashMap<SeenIdHash, bool>,
    reject_reason: Option<String>,
    do_discard: bool,
    do_deliver: bool,
    do_redirect: bool,
    pending: Option<PendingWork<'x>>,
}

enum PendingWork<'x> {
    Include {
        name: String,
    },
    DuplicateId {
        hash: SeenIdHash,
        expiry: u64,
        last: bool,
    },
    Function {
        id: u32,
        arguments: Vec<Variable<'x>>,
    },
    CreateMailbox {
        folder: String,
        flags: Vec<Keyword>,
        message_id: usize,
    },
}

impl<'x> SieveHandler<'x> {
    fn file_into(&mut self, mailbox_id: u32, flags: Vec<Keyword>, message_id: usize) {
        if let Some(message) = self.messages.get_mut(message_id) {
            message.flags = flags;
            if !message.file_into.contains(&mailbox_id) {
                message.file_into.push(mailbox_id);
            }
            self.do_deliver = true;
        } else {
            trc::event!(
                Sieve(SieveEvent::UnexpectedError),
                Details = "Unknown message id.",
                MessageId = message_id,
                SpanId = self.session_id
            );
        }
    }

    fn mailbox_by_role(&self, role: SpecialUse) -> Option<u32> {
        match role {
            SpecialUse::Inbox => Some(INBOX_ID),
            SpecialUse::Trash => Some(TRASH_ID),
            role => self.cache.mailbox_by_role(&role).map(|m| m.document_id),
        }
    }

    fn send_message(
        &mut self,
        source: MessageSource,
        recipient: Recipient<'_>,
        notify: Notify,
        message_id: usize,
    ) {
        let sender_address = if source == MessageSource::Vacation {
            ""
        } else {
            self.mail_from
        };
        let Some(message) = self.messages.get(message_id) else {
            trc::event!(
                Sieve(SieveEvent::UnexpectedError),
                Details = "Unknown message id.",
                MessageId = message_id,
                SpanId = self.session_id
            );
            return;
        };

        if self.received_headers >= self.max_received_headers {
            trc::event!(
                Smtp(SmtpEvent::LoopDetected),
                From = self.mail_from.to_string(),
                Total = self.received_headers,
                Limit = self.max_received_headers,
                SpanId = self.session_id,
            );
            return;
        }

        let recipients: Vec<String> = match recipient {
            Recipient::Address(rcpt) => vec![rcpt.to_string()],
            Recipient::Group(rcpts) => rcpts.iter().map(|rcpt| rcpt.to_string()).collect(),
            Recipient::List(_) => return,
        };

        if message.raw_message.len() > self.mail_max_size {
            trc::event!(
                Sieve(SieveEvent::MessageTooLarge),
                From = self.mail_from.to_string(),
                To = recipients
                    .iter()
                    .map(|r| trc::Value::String(r.as_str().into()))
                    .collect::<Vec<_>>(),
                Size = message.raw_message.len(),
                Limit = self.mail_max_size,
                SpanId = self.session_id,
            );
            return;
        }

        trc::event!(
            Sieve(SieveEvent::SendMessage),
            From = sender_address.to_string(),
            To = recipients
                .iter()
                .map(|r| trc::Value::String(r.as_str().into()))
                .collect::<Vec<_>>(),
            Size = message.raw_message.len(),
            SpanId = self.session_id
        );

        let mut raw_message = Vec::with_capacity(160 + message.raw_message.len());
        write_received_header(&mut raw_message, self.server_name, self.session_id);
        raw_message.extend_from_slice(message.raw_message.as_ref());

        self.autogenerated.push(AutogeneratedMessage {
            sender_address: sender_address.to_string(),
            recipients,
            message: raw_message,
            notify,
        });
        self.do_redirect = true;
    }
}

fn keywords(flags: &[&str]) -> Vec<Keyword> {
    flags
        .iter()
        .map(|flag| Keyword::try_parse(flag).unwrap_or_else(|| Keyword::from_str(flag)))
        .collect()
}

impl<'x> Handler<'x> for SieveHandler<'x> {
    fn include_script(
        &mut self,
        _: &Context<'x>,
        name: Script<'_>,
        optional: bool,
    ) -> Reply<Option<&'x Sieve<'x>>> {
        match name {
            Script::Personal(name) => {
                self.pending = Some(PendingWork::Include {
                    name: name.to_string(),
                });
                Reply::Pending
            }
            Script::Global(name) => Reply::Ready(if optional {
                self.server.core.sieve.untrusted_script(name)
            } else {
                self.server
                    .get_untrusted_sieve_script(name, self.session_id)
            }),
        }
    }

    fn mailbox_exists(
        &mut self,
        _: &Context<'x>,
        mailboxes: &[Mailbox<'_>],
        special_use: &[&str],
    ) -> Reply<bool> {
        let roles = special_use
            .iter()
            .map(|role| {
                SpecialUse::parse_use_attr(role)
                    .and_then(|role| self.mailbox_by_role(role))
                    .unwrap_or(u32::MAX)
            })
            .collect::<Vec<_>>();

        if !mailboxes.is_empty() {
            Reply::Ready(mailboxes.iter().all(|mailbox| {
                let document_id = match mailbox {
                    Mailbox::Name(name) => self.cache.mailbox_by_path(name).map(|m| m.document_id),
                    Mailbox::Id(id) => Id::from_str(id)
                        .ok()
                        .map(|id| id.document_id())
                        .filter(|id| self.cache.has_mailbox_id(id)),
                };

                document_id
                    .is_some_and(|document_id| roles.is_empty() || roles.contains(&document_id))
            }))
        } else if !special_use.is_empty() {
            Reply::Ready(!roles.contains(&u32::MAX))
        } else {
            Reply::Ready(false)
        }
    }

    fn duplicate_id(&mut self, _: &Context<'x>, id: &str, expiry: u64, last: bool) -> Reply<bool> {
        let hash = SeenIdHash::new(self.account_id, self.script_hash, id);
        match self.checked_ids.get(&hash) {
            Some(result) => Reply::Ready(*result),
            None => {
                self.pending = Some(PendingWork::DuplicateId { hash, expiry, last });
                Reply::Pending
            }
        }
    }

    fn function(
        &mut self,
        _: &Context<'x>,
        id: u32,
        arguments: &[Variable<'x>],
    ) -> Reply<Variable<'x>> {
        self.pending = Some(PendingWork::Function {
            id,
            arguments: arguments.to_vec(),
        });
        Reply::Pending
    }

    fn action(&mut self, _: &Context<'x>, action: SieveAction<'_>) -> Reply<()> {
        match action {
            SieveAction::Keep { flags, message_id } => {
                let flags = keywords(flags);
                self.file_into(INBOX_ID, flags, message_id);
            }
            SieveAction::Discard => {
                self.do_discard = true;
            }
            SieveAction::Reject { reason, .. } => {
                self.reject_reason = reason.to_string().into();
                self.do_discard = true;
            }
            SieveAction::FileInto {
                folder,
                flags,
                mailbox_id,
                special_use,
                create,
                message_id,
            } => {
                let target_id = mailbox_id
                    .and_then(|mailbox_id| Id::from_str(mailbox_id).ok())
                    .map(|mailbox_id| mailbox_id.document_id())
                    .filter(|mailbox_id| self.cache.has_mailbox_id(mailbox_id))
                    .or_else(|| {
                        special_use
                            .and_then(SpecialUse::parse_use_attr)
                            .and_then(|role| self.mailbox_by_role(role))
                    });

                let flags = keywords(flags);
                match target_id {
                    Some(target_id) => self.file_into(target_id, flags, message_id),
                    None if create => {
                        self.pending = Some(PendingWork::CreateMailbox {
                            folder: folder.to_string(),
                            flags,
                            message_id,
                        });
                        return Reply::Pending;
                    }
                    None => {
                        let target_id = self
                            .cache
                            .mailbox_by_path(folder)
                            .map_or(INBOX_ID, |mailbox| mailbox.document_id);
                        self.file_into(target_id, flags, message_id);
                    }
                }
            }
            SieveAction::SendMessage {
                source,
                recipient,
                notify,
                message_id,
                ..
            } => {
                self.send_message(source, recipient, notify, message_id);
            }
            SieveAction::CreatedMessage { message, .. } => {
                self.messages.push(SieveMessage {
                    raw_message: message.into(),
                    file_into: Vec::new(),
                    flags: Vec::new(),
                });
            }
            SieveAction::Notify { .. } | SieveAction::SetEnvelope { .. } => (),
        }

        Reply::Ready(())
    }
}

pub trait SieveScriptIngest: Sync + Send {
    #[allow(clippy::too_many_arguments)]
    fn sieve_script_ingest(
        &self,
        access_token: &AccessToken,
        blob_hash: &BlobHash,
        raw_message: &[u8],
        envelope_from: &str,
        envelope_from_authenticated: bool,
        envelope_to: &IngestRecipient,
        session_id: u64,
        active_script: ActiveScript,
        autogenerated: &mut Vec<AutogeneratedMessage>,
    ) -> impl Future<Output = trc::Result<IngestedEmail>> + Send;

    fn sieve_script_get_active_id(
        &self,
        account_id: u32,
    ) -> impl Future<Output = trc::Result<Option<u32>>> + Send;

    fn sieve_script_get_active(
        &self,
        account_id: u32,
    ) -> impl Future<Output = trc::Result<Option<ActiveScript>>> + Send;

    fn sieve_script_get_by_name(
        &self,
        account_id: u32,
        name: &str,
    ) -> impl Future<Output = trc::Result<Option<Sieve<'static>>>> + Send;

    fn sieve_script_load(
        &self,
        account_id: u32,
        document_id: u32,
    ) -> impl Future<Output = trc::Result<Option<ActiveScript>>> + Send;

    fn sieve_script_recompile(
        &self,
        account_id: u32,
        document_id: u32,
        version: ArchiveVersion,
        archive: &Archive<ArchiveBytes>,
        script_object: &ArchivedSieveScript,
    ) -> impl Future<Output = trc::Result<ActiveScript>> + Send;
}

impl SieveScriptIngest for Server {
    #[allow(clippy::blocks_in_conditions)]
    async fn sieve_script_ingest(
        &self,
        access_token: &AccessToken,
        blob_hash: &BlobHash,
        raw_message: &[u8],
        envelope_from: &str,
        envelope_from_authenticated: bool,
        envelope_to: &IngestRecipient,
        session_id: u64,
        active_script: ActiveScript,
        autogenerated: &mut Vec<AutogeneratedMessage>,
    ) -> trc::Result<IngestedEmail> {
        // Parse message
        let message = MessageParser::new().parse(raw_message).ok_or_else(|| {
            trc::EventType::MessageIngest(trc::MessageIngestEvent::Error)
                .ctx(trc::Key::Code, 550)
                .ctx(trc::Key::Reason, "Failed to parse e-mail message.")
        })?;

        let received_headers = message
            .headers()
            .iter()
            .filter(|header| matches!(header.name, HeaderName::Received))
            .count();

        // Obtain mailboxIds
        let account_id = access_token.account_id();
        let cache = self
            .get_cached_messages(account_id)
            .await
            .caused_by(trc::location!())?;

        // Set account name and email
        let account_info = self.account(account_id).await.caused_by(trc::location!())?;
        let mail_from = account_info.name();

        // Load the compiled script
        let included = ScriptArena::new();
        let mut resolved_includes: Vec<(String, &Sieve<'static>)> = Vec::new();
        let script = Sieve::from_bytes(active_script.bytecode()?).map_err(|err| {
            trc::StoreEvent::UnexpectedError
                .caused_by(trc::location!())
                .reason(err)
                .details("Failed to load compiled Sieve script")
        })?;

        // Create Sieve instance
        let mut arena = Arena::new();
        let mut ctx = self
            .core
            .sieve
            .untrusted_runtime
            .filter_parsed(message, &script, &mut arena);
        ctx.set_user_full_name(
            account_info
                .description()
                .unwrap_or_else(|| account_info.name()),
        );
        ctx.set_user_address(mail_from);
        ctx.set_envelope(Envelope::From, envelope_from);
        ctx.set_envelope(Envelope::To, envelope_to.address.as_str());
        if let Some(orcpt) = &envelope_to.orcpt {
            ctx.set_envelope(Envelope::Orcpt, orcpt.as_str());
        }
        ctx.set_spam_status(spam_status(envelope_to.spam_percentage));

        let mut handler = SieveHandler {
            server: self,
            session_id,
            account_id,
            script_hash: active_script.version.hash().unwrap_or_default(),
            cache,
            mail_from,
            server_name: self.core.network.server_name.as_str(),
            mail_max_size: self.core.email.mail_max_size,
            max_received_headers: self.core.sieve.max_received_headers,
            received_headers,
            messages: vec![SieveMessage {
                raw_message: raw_message.into(),
                file_into: Vec::new(),
                flags: Vec::new(),
            }],
            autogenerated,
            checked_ids: AHashMap::new(),
            reject_reason: None,
            do_discard: false,
            do_deliver: false,
            do_redirect: false,
            pending: None,
        };

        let mut ingested_message = IngestedEmail {
            document_id: 0,
            thread_id: 0,
            change_id: u64::MAX,
            blob_id: Default::default(),
            size: raw_message.len(),
            imap_uids: Vec::new(),
        };

        loop {
            match ctx.run(&mut handler) {
                Ok(Status::Finished) => break,
                Ok(Status::Pending) => {
                    let input = match handler.pending.take() {
                        Some(PendingWork::Include { name }) => {
                            let script = if let Some((_, script)) = resolved_includes
                                .iter()
                                .find(|(resolved, _)| *resolved == name)
                            {
                                Some(*script)
                            } else if let Some(script) =
                                self.sieve_script_get_by_name(account_id, &name).await?
                            {
                                let script = included.push(script);
                                resolved_includes.push((name, script));
                                Some(script)
                            } else {
                                None
                            };

                            Input::Script(script)
                        }
                        Some(PendingWork::DuplicateId { hash, expiry, last }) => {
                            let exists = self
                                .in_memory_store()
                                .key_exists(hash.key())
                                .await
                                .caused_by(trc::location!())?;

                            if !exists || last {
                                self.in_memory_store()
                                    .key_set(KeyValue::new(hash.key(), vec![]).expires(expiry))
                                    .await
                                    .caused_by(trc::location!())?;
                            }

                            handler.checked_ids.insert(hash, exists);

                            Input::Bool(exists)
                        }
                        Some(PendingWork::Function { id, arguments }) => {
                            self.core
                                .run_plugin(
                                    id,
                                    PluginContext {
                                        session_id,
                                        server: self,
                                        message: ctx.message(),
                                        modifications: &mut Vec::new(),
                                        access_token: access_token.into(),
                                        arguments,
                                    },
                                )
                                .await
                        }
                        Some(PendingWork::CreateMailbox {
                            folder,
                            flags,
                            message_id,
                        }) => {
                            let target_id = match self
                                .mailbox_create_path(account_id, &folder)
                                .await
                                .caused_by(trc::location!())?
                            {
                                Some(document_id) => {
                                    handler.cache = self
                                        .get_cached_messages(account_id)
                                        .await
                                        .caused_by(trc::location!())?;
                                    document_id
                                }
                                None => INBOX_ID,
                            };
                            handler.file_into(target_id, flags, message_id);

                            Input::Continue
                        }
                        None => Input::Continue,
                    };

                    ctx.resume(input);
                }

                #[cfg(feature = "test_mode")]
                Err(sieve::runtime::RuntimeError::ScriptErrorMessage(err)) => {
                    panic!("Sieve test failed: {}", err);
                }

                Err(err) => {
                    trc::event!(
                        Sieve(SieveEvent::RuntimeError),
                        Reason = err.to_string(),
                        SpanId = session_id
                    );
                }
            }
        }

        let SieveHandler {
            mut messages,
            reject_reason,
            do_discard,
            do_deliver,
            do_redirect,
            ..
        } = handler;

        // Fail-safe, no discard and no keep seen, assume that something went wrong and file anyway.
        if !do_deliver
            && !do_discard
            && !do_redirect
            && let Some(message) = messages.first_mut()
        {
            message.file_into.push(INBOX_ID);
        }

        // Deliver messages
        let mut last_temp_error = None;
        let mut has_delivered = false;
        for (message_id, sieve_message) in messages.into_iter().enumerate() {
            if !sieve_message.file_into.is_empty() {
                // Parse message if needed
                let (blob_hash, message) = if message_id == 0 && !ctx.has_message_changed() {
                    (blob_hash.into(), ctx.take_message())
                } else if let Some(message) =
                    MessageParser::new().parse(sieve_message.raw_message.as_ref())
                {
                    (None, message)
                } else {
                    trc::event!(
                        Sieve(SieveEvent::UnexpectedError),
                        Details = "Failed to parse Sieve generated message.",
                        SpanId = session_id
                    );

                    continue;
                };

                // Deliver message
                match self
                    .email_ingest(IngestEmail {
                        raw_message: &sieve_message.raw_message,
                        blob_hash,
                        message: message.into(),
                        access_token,
                        mailbox_ids: sieve_message.file_into,
                        keywords: sieve_message.flags,
                        received_at: None,
                        source: IngestSource::Smtp {
                            deliver_to: envelope_to.address.as_str(),
                            is_sender_authenticated: envelope_from_authenticated,
                            is_spam: envelope_to.is_spam(),
                        },
                        session_id,
                    })
                    .await
                {
                    Ok(ingested_message_) => {
                        has_delivered = true;
                        ingested_message = ingested_message_;
                    }
                    Err(err) => {
                        last_temp_error = err.into();
                    }
                }
            }
        }

        if let Some(reject_reason) = reject_reason {
            Err(
                trc::EventType::MessageIngest(trc::MessageIngestEvent::Error)
                    .ctx(trc::Key::Code, 571)
                    .ctx(trc::Key::Reason, reject_reason),
            )
        } else if has_delivered || last_temp_error.is_none() {
            Ok(ingested_message)
        } else {
            // There were problems during delivery
            #[allow(clippy::unnecessary_unwrap)]
            Err(last_temp_error.unwrap())
        }
    }

    async fn sieve_script_get_active_id(&self, account_id: u32) -> trc::Result<Option<u32>> {
        self.store()
            .get_value::<u32>(ValueKey {
                account_id,
                collection: Collection::Principal.into(),
                document_id: 0,
                class: ValueClass::Property(PrincipalField::ActiveScriptId.into()),
            })
            .await
            .caused_by(trc::location!())
    }

    async fn sieve_script_get_active(&self, account_id: u32) -> trc::Result<Option<ActiveScript>> {
        // Find the currently active script
        if let Some(document_id) = self
            .sieve_script_get_active_id(account_id)
            .await
            .caused_by(trc::location!())?
        {
            self.sieve_script_load(account_id, document_id).await
        } else {
            Ok(None)
        }
    }

    async fn sieve_script_get_by_name(
        &self,
        account_id: u32,
        name: &str,
    ) -> trc::Result<Option<Sieve<'static>>> {
        // Find the script by name
        let Some(document_id) = self
            .document_ids_matching(
                account_id,
                Collection::SieveScript,
                SieveField::Name,
                name.to_lowercase().as_bytes(),
            )
            .await
            .caused_by(trc::location!())?
            .min()
        else {
            return Ok(None);
        };

        let Some(active_script) = self.sieve_script_load(account_id, document_id).await? else {
            return Ok(None);
        };

        Sieve::from_bytes(active_script.bytecode()?)
            .map(|script| Some(script.into_owned()))
            .map_err(|err| {
                trc::StoreEvent::UnexpectedError
                    .caused_by(trc::location!())
                    .reason(err)
                    .details("Failed to load compiled Sieve script")
            })
    }

    async fn sieve_script_load(
        &self,
        account_id: u32,
        document_id: u32,
    ) -> trc::Result<Option<ActiveScript>> {
        // Obtain script object
        let Some(archive) = self
            .store()
            .get_value::<Archive<ArchiveBytes>>(ValueKey::archive(
                account_id,
                Collection::SieveScript,
                document_id,
            ))
            .await?
        else {
            return Ok(None);
        };

        let version = archive.version;
        let script_object = archive
            .unarchive::<SieveScript>()
            .caused_by(trc::location!())?;

        if Sieve::from_bytes(script_object.script.as_ref()).is_ok() {
            Ok(Some(ActiveScript {
                document_id,
                version,
                script_name: script_object.name.to_string(),
                script: Bytecode::Stored(archive),
            }))
        } else {
            self.sieve_script_recompile(account_id, document_id, version, &archive, script_object)
                .await
                .map(Some)
        }
    }

    async fn sieve_script_recompile(
        &self,
        account_id: u32,
        document_id: u32,
        version: ArchiveVersion,
        archive: &Archive<ArchiveBytes>,
        script_object: &ArchivedSieveScript,
    ) -> trc::Result<ActiveScript> {
        let script_bytes = self
            .blob_store()
            .get_blob(script_object.blob_hash.0.as_ref(), 0..usize::MAX)
            .await
            .caused_by(trc::location!())?
            .ok_or_else(|| {
                trc::StoreEvent::NotFound
                    .into_err()
                    .caused_by(trc::location!())
                    .document_id(document_id)
            })?;

        let script = self
            .core
            .sieve
            .untrusted_compiler
            .compile(&script_bytes)
            .map_err(|err| {
                trc::StoreEvent::UnexpectedError
                    .caused_by(trc::location!())
                    .reason(err)
                    .details("Failed to compile Sieve script")
            })?;

        let new_script_object = SieveScript {
            name: script_object.name.to_string(),
            blob_hash: BlobHash::from(&script_object.blob_hash),
            size: script_object.size.to_native(),
            vacation_response: script_object.vacation_response.as_ref().map(|vr| {
                VacationResponse {
                    from_date: vr.from_date.as_ref().map(|v| v.to_native()),
                    to_date: vr.to_date.as_ref().map(|v| v.to_native()),
                    subject: vr.subject.as_ref().map(|v| v.to_string()),
                    text_body: vr.text_body.as_ref().map(|v| v.to_string()),
                    html_body: vr.html_body.as_ref().map(|v| v.to_string()),
                }
            }),
            script: script.to_bytes(),
        };
        let script_name = new_script_object.name.clone();
        let bytecode = new_script_object.script.clone();
        let bytes = Archiver::new(new_script_object)
            .serialize()
            .caused_by(trc::location!())?;

        let mut batch = BatchBuilder::new();
        batch
            .with_account_id(account_id)
            .with_collection(Collection::SieveScript)
            .with_document(document_id)
            .assert_value(SieveField::Archive, archive)
            .set(SieveField::Archive, bytes);
        self.commit_batch(batch).await.caused_by(trc::location!())?;

        Ok(ActiveScript {
            document_id,
            version,
            script_name,
            script: Bytecode::Compiled(bytecode),
        })
    }
}

fn write_received_header(buf: &mut Vec<u8>, hostname: &str, id: u64) {
    buf.extend_from_slice(b"Received: from localhost (localhost [127.0.0.1])\r\n\tby ");
    buf.extend_from_slice(hostname.as_bytes());
    buf.extend_from_slice(b" (Stalwart SMTP) with LMTP id ");
    buf.extend_from_slice(format!("{id:X}").as_bytes());
    buf.extend_from_slice(b";\r\n\t");
    buf.extend_from_slice(Date::now().to_rfc822().as_bytes());
    buf.extend_from_slice(b"\r\n");
}
