/*
 * SPDX-FileCopyrightText: 2020 Stalwart Labs LLC <hello@stalw.art>
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-SEL
 */

use super::cid::CidCollection;
use super::cmaps::{CmapDecoder, CmapInfo, CodeRange};

pub(super) static CMAP_NAMES: &str = "83pv-RKSJ-H90ms-RKSJ-H90ms-RKSJ-V90msp-RKSJ-H90msp-RKSJ-V90pv-RKSJ-H90pv-RKSJ-VAdd-RKSJ-HAdd-RKSJ-VB5pc-HB5pc-VCNS-EUC-HCNS-EUC-VETen-B5-HETen-B5-VETenms-B5-HETenms-B5-VEUC-HEUC-VExt-RKSJ-HExt-RKSJ-VGB-EUC-HGB-EUC-VGBK-EUC-HGBK-EUC-VGBK2K-HGBK2K-VGBKp-EUC-HGBKp-EUC-VGBpc-EUC-HGBpc-EUC-VHHKscs-B5-HHKscs-B5-VIdentity-HIdentity-VKSC-EUC-HKSC-EUC-VKSCms-UHC-HKSCms-UHC-HW-HKSCms-UHC-HW-VKSCms-UHC-VKSCpc-EUC-HKSCpc-EUC-VUniCNS-UCS2-HUniCNS-UCS2-VUniCNS-UTF16-HUniCNS-UTF16-VUniCNS-UTF32-HUniCNS-UTF32-VUniCNS-UTF8-HUniCNS-UTF8-VUniGB-UCS2-HUniGB-UCS2-VUniGB-UTF16-HUniGB-UTF16-VUniGB-UTF32-HUniGB-UTF32-VUniGB-UTF8-HUniGB-UTF8-VUniJIS-UCS2-HUniJIS-UCS2-HW-HUniJIS-UCS2-HW-VUniJIS-UCS2-VUniJIS-UTF16-HUniJIS-UTF16-VUniJIS-UTF32-HUniJIS-UTF32-VUniJIS-UTF8-HUniJIS-UTF8-VUniKS-UCS2-HUniKS-UCS2-VUniKS-UTF16-HUniKS-UTF16-VUniKS-UTF32-HUniKS-UTF32-VUniKS-UTF8-HUniKS-UTF8-VV";
pub(super) static CMAP_OFFSETS: [u16; 80] = [
    0, 11, 22, 33, 45, 57, 68, 79, 89, 99, 105, 111, 120, 129, 138, 147, 158, 169, 174, 179, 189,
    199, 207, 215, 224, 233, 240, 247, 257, 267, 277, 287, 288, 298, 308, 318, 328, 337, 346, 357,
    371, 385, 396, 407, 418, 431, 444, 458, 472, 486, 500, 513, 526, 538, 550, 563, 576, 589, 602,
    614, 626, 639, 655, 671, 684, 698, 712, 726, 740, 753, 766, 778, 790, 803, 816, 829, 842, 854,
    866, 867,
];

pub(super) static CMAP_INFO: [CmapInfo; 79] = [
    CmapInfo {
        ranges: 0,
        range_count: 5,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 0,
        patch_count: 5,
    },
    CmapInfo {
        ranges: 5,
        range_count: 4,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 5,
        patch_count: 1,
    },
    CmapInfo {
        ranges: 5,
        range_count: 4,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 5,
        patch_count: 1,
    },
    CmapInfo {
        ranges: 5,
        range_count: 4,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 5,
        patch_count: 1,
    },
    CmapInfo {
        ranges: 5,
        range_count: 4,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 5,
        patch_count: 1,
    },
    CmapInfo {
        ranges: 0,
        range_count: 5,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 0,
        patch_count: 5,
    },
    CmapInfo {
        ranges: 0,
        range_count: 5,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 0,
        patch_count: 5,
    },
    CmapInfo {
        ranges: 5,
        range_count: 4,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 5,
        patch_count: 1,
    },
    CmapInfo {
        ranges: 5,
        range_count: 4,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 5,
        patch_count: 1,
    },
    CmapInfo {
        ranges: 9,
        range_count: 3,
        decoder: CmapDecoder::Big5,
        collection: Some(CidCollection::Cns1),
        vertical: false,
        patches: 6,
        patch_count: 4,
    },
    CmapInfo {
        ranges: 9,
        range_count: 3,
        decoder: CmapDecoder::Big5,
        collection: Some(CidCollection::Cns1),
        vertical: true,
        patches: 6,
        patch_count: 4,
    },
    CmapInfo {
        ranges: 12,
        range_count: 5,
        decoder: CmapDecoder::EucTw,
        collection: Some(CidCollection::Cns1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 12,
        range_count: 5,
        decoder: CmapDecoder::EucTw,
        collection: Some(CidCollection::Cns1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 17,
        range_count: 2,
        decoder: CmapDecoder::Big5,
        collection: Some(CidCollection::Cns1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 17,
        range_count: 2,
        decoder: CmapDecoder::Big5,
        collection: Some(CidCollection::Cns1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 17,
        range_count: 2,
        decoder: CmapDecoder::Big5,
        collection: Some(CidCollection::Cns1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 17,
        range_count: 2,
        decoder: CmapDecoder::Big5,
        collection: Some(CidCollection::Cns1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 19,
        range_count: 3,
        decoder: CmapDecoder::EucJp,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 19,
        range_count: 3,
        decoder: CmapDecoder::EucJp,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 5,
        range_count: 4,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 5,
        patch_count: 1,
    },
    CmapInfo {
        ranges: 5,
        range_count: 4,
        decoder: CmapDecoder::ShiftJis,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 5,
        patch_count: 1,
    },
    CmapInfo {
        ranges: 22,
        range_count: 2,
        decoder: CmapDecoder::Gbk,
        collection: Some(CidCollection::Gb1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 22,
        range_count: 2,
        decoder: CmapDecoder::Gbk,
        collection: Some(CidCollection::Gb1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 24,
        range_count: 2,
        decoder: CmapDecoder::Gbk,
        collection: Some(CidCollection::Gb1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 24,
        range_count: 2,
        decoder: CmapDecoder::Gbk,
        collection: Some(CidCollection::Gb1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 26,
        range_count: 3,
        decoder: CmapDecoder::Gb18030,
        collection: Some(CidCollection::Gb1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 26,
        range_count: 3,
        decoder: CmapDecoder::Gb18030,
        collection: Some(CidCollection::Gb1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 24,
        range_count: 2,
        decoder: CmapDecoder::Gbk,
        collection: Some(CidCollection::Gb1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 24,
        range_count: 2,
        decoder: CmapDecoder::Gbk,
        collection: Some(CidCollection::Gb1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 29,
        range_count: 3,
        decoder: CmapDecoder::Gbk,
        collection: Some(CidCollection::Gb1),
        vertical: false,
        patches: 10,
        patch_count: 4,
    },
    CmapInfo {
        ranges: 29,
        range_count: 3,
        decoder: CmapDecoder::Gbk,
        collection: Some(CidCollection::Gb1),
        vertical: true,
        patches: 10,
        patch_count: 4,
    },
    CmapInfo {
        ranges: 32,
        range_count: 1,
        decoder: CmapDecoder::JisRowCell,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 33,
        range_count: 2,
        decoder: CmapDecoder::Big5,
        collection: Some(CidCollection::Cns1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 33,
        range_count: 2,
        decoder: CmapDecoder::Big5,
        collection: Some(CidCollection::Cns1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 35,
        range_count: 1,
        decoder: CmapDecoder::Identity,
        collection: None,
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 35,
        range_count: 1,
        decoder: CmapDecoder::Identity,
        collection: None,
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 22,
        range_count: 2,
        decoder: CmapDecoder::EucKr,
        collection: Some(CidCollection::Korea1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 22,
        range_count: 2,
        decoder: CmapDecoder::EucKr,
        collection: Some(CidCollection::Korea1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 36,
        range_count: 2,
        decoder: CmapDecoder::EucKr,
        collection: Some(CidCollection::Korea1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 36,
        range_count: 2,
        decoder: CmapDecoder::EucKr,
        collection: Some(CidCollection::Korea1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 36,
        range_count: 2,
        decoder: CmapDecoder::EucKr,
        collection: Some(CidCollection::Korea1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 36,
        range_count: 2,
        decoder: CmapDecoder::EucKr,
        collection: Some(CidCollection::Korea1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 38,
        range_count: 3,
        decoder: CmapDecoder::EucKr,
        collection: Some(CidCollection::Korea1),
        vertical: false,
        patches: 14,
        patch_count: 5,
    },
    CmapInfo {
        ranges: 38,
        range_count: 3,
        decoder: CmapDecoder::EucKr,
        collection: Some(CidCollection::Korea1),
        vertical: true,
        patches: 14,
        patch_count: 5,
    },
    CmapInfo {
        ranges: 41,
        range_count: 2,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Cns1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 41,
        range_count: 2,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Cns1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 43,
        range_count: 3,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Cns1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 43,
        range_count: 3,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Cns1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 46,
        range_count: 1,
        decoder: CmapDecoder::Utf32Be,
        collection: Some(CidCollection::Cns1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 46,
        range_count: 1,
        decoder: CmapDecoder::Utf32Be,
        collection: Some(CidCollection::Cns1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 47,
        range_count: 4,
        decoder: CmapDecoder::Utf8,
        collection: Some(CidCollection::Cns1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 47,
        range_count: 4,
        decoder: CmapDecoder::Utf8,
        collection: Some(CidCollection::Cns1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 41,
        range_count: 2,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Gb1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 41,
        range_count: 2,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Gb1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 43,
        range_count: 3,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Gb1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 43,
        range_count: 3,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Gb1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 46,
        range_count: 1,
        decoder: CmapDecoder::Utf32Be,
        collection: Some(CidCollection::Gb1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 46,
        range_count: 1,
        decoder: CmapDecoder::Utf32Be,
        collection: Some(CidCollection::Gb1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 47,
        range_count: 4,
        decoder: CmapDecoder::Utf8,
        collection: Some(CidCollection::Gb1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 47,
        range_count: 4,
        decoder: CmapDecoder::Utf8,
        collection: Some(CidCollection::Gb1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 41,
        range_count: 2,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 41,
        range_count: 2,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 41,
        range_count: 2,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 41,
        range_count: 2,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 43,
        range_count: 3,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 43,
        range_count: 3,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 46,
        range_count: 1,
        decoder: CmapDecoder::Utf32Be,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 46,
        range_count: 1,
        decoder: CmapDecoder::Utf32Be,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 47,
        range_count: 4,
        decoder: CmapDecoder::Utf8,
        collection: Some(CidCollection::Japan1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 47,
        range_count: 4,
        decoder: CmapDecoder::Utf8,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 41,
        range_count: 2,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Korea1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 41,
        range_count: 2,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Korea1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 43,
        range_count: 3,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Korea1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 43,
        range_count: 3,
        decoder: CmapDecoder::Utf16Be,
        collection: Some(CidCollection::Korea1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 46,
        range_count: 1,
        decoder: CmapDecoder::Utf32Be,
        collection: Some(CidCollection::Korea1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 46,
        range_count: 1,
        decoder: CmapDecoder::Utf32Be,
        collection: Some(CidCollection::Korea1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 47,
        range_count: 4,
        decoder: CmapDecoder::Utf8,
        collection: Some(CidCollection::Korea1),
        vertical: false,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 47,
        range_count: 4,
        decoder: CmapDecoder::Utf8,
        collection: Some(CidCollection::Korea1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
    CmapInfo {
        ranges: 32,
        range_count: 1,
        decoder: CmapDecoder::JisRowCell,
        collection: Some(CidCollection::Japan1),
        vertical: true,
        patches: 10,
        patch_count: 0,
    },
];

pub(super) static CODE_RANGES: [CodeRange; 51] = [
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(1, [0xA0, 0x00, 0x00, 0x00], [0xDF, 0x00, 0x00, 0x00]),
    CodeRange::new(1, [0xFD, 0x00, 0x00, 0x00], [0xFF, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0x81, 0x40, 0x00, 0x00], [0x9F, 0xFC, 0x00, 0x00]),
    CodeRange::new(2, [0xE0, 0x40, 0x00, 0x00], [0xFC, 0xFC, 0x00, 0x00]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(1, [0xA0, 0x00, 0x00, 0x00], [0xDF, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0x81, 0x40, 0x00, 0x00], [0x9F, 0xFC, 0x00, 0x00]),
    CodeRange::new(2, [0xE0, 0x40, 0x00, 0x00], [0xFC, 0xFC, 0x00, 0x00]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(1, [0xFD, 0x00, 0x00, 0x00], [0xFF, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0xA1, 0x40, 0x00, 0x00], [0xFC, 0xFE, 0x00, 0x00]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0xA1, 0xA1, 0x00, 0x00], [0xFE, 0xFE, 0x00, 0x00]),
    CodeRange::new(4, [0x8E, 0xA1, 0xA1, 0xA1], [0x8E, 0xA1, 0xFE, 0xFE]),
    CodeRange::new(4, [0x8E, 0xA2, 0xA1, 0xA1], [0x8E, 0xA2, 0xFE, 0xFE]),
    CodeRange::new(4, [0x8E, 0xA3, 0xA1, 0xA1], [0x8E, 0xA3, 0xFE, 0xFE]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0xA1, 0x40, 0x00, 0x00], [0xFE, 0xFE, 0x00, 0x00]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0x8E, 0xA0, 0x00, 0x00], [0x8E, 0xDF, 0x00, 0x00]),
    CodeRange::new(2, [0xA1, 0xA1, 0x00, 0x00], [0xFE, 0xFE, 0x00, 0x00]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0xA1, 0xA1, 0x00, 0x00], [0xFE, 0xFE, 0x00, 0x00]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0x81, 0x40, 0x00, 0x00], [0xFE, 0xFE, 0x00, 0x00]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x7F, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0x81, 0x40, 0x00, 0x00], [0xFE, 0xFE, 0x00, 0x00]),
    CodeRange::new(4, [0x81, 0x30, 0x81, 0x30], [0xFE, 0x39, 0xFE, 0x39]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(1, [0xFD, 0x00, 0x00, 0x00], [0xFF, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0xA1, 0xA1, 0x00, 0x00], [0xFC, 0xFE, 0x00, 0x00]),
    CodeRange::new(2, [0x21, 0x21, 0x00, 0x00], [0x7E, 0x7E, 0x00, 0x00]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0x87, 0x40, 0x00, 0x00], [0xFE, 0xFE, 0x00, 0x00]),
    CodeRange::new(2, [0x00, 0x00, 0x00, 0x00], [0xFF, 0xFF, 0x00, 0x00]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x80, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0x81, 0x41, 0x00, 0x00], [0xFE, 0xFE, 0x00, 0x00]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x84, 0x00, 0x00, 0x00]),
    CodeRange::new(1, [0xFE, 0x00, 0x00, 0x00], [0xFF, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0xA1, 0x41, 0x00, 0x00], [0xFD, 0xFE, 0x00, 0x00]),
    CodeRange::new(2, [0x00, 0x00, 0x00, 0x00], [0xD7, 0xFF, 0x00, 0x00]),
    CodeRange::new(2, [0xE0, 0x00, 0x00, 0x00], [0xFF, 0xFF, 0x00, 0x00]),
    CodeRange::new(2, [0x00, 0x00, 0x00, 0x00], [0xD7, 0xFF, 0x00, 0x00]),
    CodeRange::new(2, [0xE0, 0x00, 0x00, 0x00], [0xFF, 0xFF, 0x00, 0x00]),
    CodeRange::new(4, [0xD8, 0x00, 0xDC, 0x00], [0xDB, 0xFF, 0xDF, 0xFF]),
    CodeRange::new(4, [0x00, 0x00, 0x00, 0x00], [0x00, 0x10, 0xFF, 0xFF]),
    CodeRange::new(1, [0x00, 0x00, 0x00, 0x00], [0x7F, 0x00, 0x00, 0x00]),
    CodeRange::new(2, [0xC0, 0x80, 0x00, 0x00], [0xDF, 0xBF, 0x00, 0x00]),
    CodeRange::new(3, [0xE0, 0x80, 0x80, 0x00], [0xEF, 0xBF, 0xBF, 0x00]),
    CodeRange::new(4, [0xF0, 0x80, 0x80, 0x80], [0xF7, 0xBF, 0xBF, 0xBF]),
];

pub(super) static PATCH_BYTES: [u8; 19] = [
    0x80, 0xA0, 0xFD, 0xFE, 0xFF, 0xA0, 0x80, 0xFD, 0xFE, 0xFF, 0x80, 0xFD, 0xFE, 0xFF, 0x81, 0x82,
    0x83, 0xFE, 0xFF,
];
pub(super) static PATCH_CHARS: [char; 19] = [
    '\u{5c}', '\u{ff60}', '\u{a9}', '\u{2122}', '\u{2026}', '\u{ff60}', '\u{5c}', '\u{a9}',
    '\u{2122}', '\u{2026}', '\u{fc}', '\u{a9}', '\u{2122}', '\u{2026}', '\u{20a9}', '\u{2010}',
    '\u{a9}', '\u{2122}', '\u{22ef}',
];
