[package]
name = "stalwart-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
imap_proto = { path = "../crates/imap-proto" }
nlp = { path = "../crates/nlp" }
spam-filter = { path = "../crates/spam-filter" }
common = { path = "../crates/common" }
utils = { path = "../crates/utils" }
types = { path = "../crates/types" }
dav-proto = { path = "../crates/dav-proto" }
jmap-tools = "0.1"
mail-parser = { version = "0.11", features = ["full_encoding"] }
encodify = "1.0"

[workspace]

[patch.crates-io]
calcard = { path = "../../calcard" }
dns-update = { path = "../../dns-update" }
jmap-tools = { path = "../../jmap-tools" }
mail-auth = { path = "../../mail-auth" }
mail-builder = { path = "../../mail-builder" }
encodify = { path = "../../encodify" }
mail-parser = { path = "../../mail-parser" }
sieve-rs = { path = "../../sieve" }

[[bin]]
name = "imap_receiver"
path = "fuzz_targets/imap_receiver.rs"
test = false
doc = false
bench = false

[[bin]]
name = "imap_utf7"
path = "fuzz_targets/imap_utf7.rs"
test = false
doc = false
bench = false

[[bin]]
name = "nlp_types"
path = "fuzz_targets/nlp_types.rs"
test = false
doc = false
bench = false

[[bin]]
name = "nlp_word_space"
path = "fuzz_targets/nlp_word_space.rs"
test = false
doc = false
bench = false

[[bin]]
name = "spam_html"
path = "fuzz_targets/spam_html.rs"
test = false
doc = false
bench = false

[[bin]]
name = "spam_normalizers"
path = "fuzz_targets/spam_normalizers.rs"
test = false
doc = false
bench = false

[[bin]]
name = "spam_context"
path = "fuzz_targets/spam_context.rs"
test = false
doc = false
bench = false

[[bin]]
name = "metadata_container"
path = "fuzz_targets/metadata_container.rs"
test = false
doc = false
bench = false

[[bin]]
name = "dav_xml_value"
path = "fuzz_targets/dav_xml_value.rs"
test = false
doc = false
bench = false
