/*
 * SPDX-FileCopyrightText: 2020 Stalwart Labs LLC <hello@stalw.art>
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-SEL
 */

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Word {
    Ansi,
    AnsiCodePage,
    Mac,
    DefaultFont,
    FromHtml,
    HtmlRtf,
    FontTable,
    Font,
    FontCharset,
    FontCodePage,
    Plain,
    UnicodeSkip,
    Unicode,
    UnicodeDestination,
    ShapeInstructions,
    Bin,
    Paragraph,
    Tab,
    Character(char),
    Destination,
}

impl Word {
    pub(crate) fn parse(name: &[u8]) -> Option<Word> {
        hashify::tiny_map!(name,
            b"ansi" => Word::Ansi,
            b"ansicpg" => Word::AnsiCodePage,
            b"mac" => Word::Mac,
            b"deff" => Word::DefaultFont,
            b"fromhtml" => Word::FromHtml,
            b"htmlrtf" => Word::HtmlRtf,
            b"fonttbl" => Word::FontTable,
            b"f" => Word::Font,
            b"fcharset" => Word::FontCharset,
            b"cpg" => Word::FontCodePage,
            b"plain" => Word::Plain,
            b"uc" => Word::UnicodeSkip,
            b"u" => Word::Unicode,
            b"ud" => Word::UnicodeDestination,
            b"shpinst" => Word::ShapeInstructions,
            b"bin" => Word::Bin,
            b"par" => Word::Paragraph,
            b"line" => Word::Paragraph,
            b"lbr" => Word::Paragraph,
            b"sect" => Word::Paragraph,
            b"page" => Word::Paragraph,
            b"row" => Word::Paragraph,
            b"nestrow" => Word::Paragraph,
            b"column" => Word::Paragraph,
            b"tab" => Word::Tab,
            b"cell" => Word::Tab,
            b"nestcell" => Word::Tab,
            b"emdash" => Word::Character('\u{2014}'),
            b"endash" => Word::Character('\u{2013}'),
            b"lquote" => Word::Character('\u{2018}'),
            b"rquote" => Word::Character('\u{2019}'),
            b"ldblquote" => Word::Character('\u{201C}'),
            b"rdblquote" => Word::Character('\u{201D}'),
            b"bullet" => Word::Character('\u{2022}'),
            b"emspace" => Word::Character(' '),
            b"enspace" => Word::Character(' '),
            b"qmspace" => Word::Character(' '),
            b"aftnsep" => Word::Destination,
            b"aftnsepc" => Word::Destination,
            b"author" => Word::Destination,
            b"bkmkend" => Word::Destination,
            b"bkmkstart" => Word::Destination,
            b"blipuid" => Word::Destination,
            b"colortbl" => Word::Destination,
            b"colorschememapping" => Word::Destination,
            b"datastore" => Word::Destination,
            b"defchp" => Word::Destination,
            b"defpap" => Word::Destination,
            b"docvar" => Word::Destination,
            b"falt" => Word::Destination,
            b"fchars" => Word::Destination,
            b"filetbl" => Word::Destination,
            b"fldinst" => Word::Destination,
            b"ftnsep" => Word::Destination,
            b"ftnsepc" => Word::Destination,
            b"generator" => Word::Destination,
            b"htmltag" => Word::Destination,
            b"info" => Word::Destination,
            b"latentstyles" => Word::Destination,
            b"lchars" => Word::Destination,
            b"levelnumbers" => Word::Destination,
            b"leveltext" => Word::Destination,
            b"listoverridetable" => Word::Destination,
            b"listtable" => Word::Destination,
            b"listtext" => Word::Destination,
            b"mhtmltag" => Word::Destination,
            b"mmathPr" => Word::Destination,
            b"nonshppict" => Word::Destination,
            b"objclass" => Word::Destination,
            b"objdata" => Word::Destination,
            b"operator" => Word::Destination,
            b"panose" => Word::Destination,
            b"pgdsctbl" => Word::Destination,
            b"pict" => Word::Destination,
            b"pntext" => Word::Destination,
            b"pntxta" => Word::Destination,
            b"pntxtb" => Word::Destination,
            b"protusertbl" => Word::Destination,
            b"revtbl" => Word::Destination,
            b"rsidtbl" => Word::Destination,
            b"shprslt" => Word::Destination,
            b"sp" => Word::Destination,
            b"stylesheet" => Word::Destination,
            b"tc" => Word::Destination,
            b"template" => Word::Destination,
            b"themedata" => Word::Destination,
            b"upr" => Word::Destination,
            b"userprops" => Word::Destination,
            b"wgrffmtfilter" => Word::Destination,
            b"xe" => Word::Destination,
            b"xmlnstbl" => Word::Destination,
        )
    }
}
